on:
  pull_request:
    types: [opened, edited]

jobs:
  label_regex:
    runs-on: ubuntu-latest
    name: Add label
    steps:
      - name: "Assign label to new Pull Request"
        uses: Bhacaz/label-regex@v2.1
        with:
          field: title
          regex: '^chore\(.*(deps)\)|^(fix|hotfix|feat|docs|breaking)?'
          token: ${{ github.token }}
